// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonelApi.Data;

#nullable disable

namespace PersonelApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304072826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PersonelApi.Models.Birim", b =>
                {
                    b.Property<int>("BirimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BirimAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BirimId");

                    b.ToTable("Birimler");
                });

            modelBuilder.Entity("PersonelApi.Models.Cocuk", b =>
                {
                    b.Property<int>("CocukId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("DogumYeri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CocukId");

                    b.ToTable("Cocuklar");
                });

            modelBuilder.Entity("PersonelApi.Models.Gorevlendirme", b =>
                {
                    b.Property<int>("GorevlendirmeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjeNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GorevlendirmeId");

                    b.ToTable("Gorevlendirmeler");
                });

            modelBuilder.Entity("PersonelApi.Models.Il", b =>
                {
                    b.Property<int>("IlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IlAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IlId");

                    b.ToTable("Iller");
                });

            modelBuilder.Entity("PersonelApi.Models.Ilce", b =>
                {
                    b.Property<int>("IlceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IlId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IlceAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IlceId");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("PersonelApi.Models.Personel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BaslamaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("BirimId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CalismaSaati")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("DogumYeri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Maas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Prim")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnvanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonelId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("PersonelApi.Models.Proje", b =>
                {
                    b.Property<int>("ProjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BaslamaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjeAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProjeId");

                    b.ToTable("Projeler");
                });

            modelBuilder.Entity("PersonelApi.Models.Unvan", b =>
                {
                    b.Property<int>("UnvanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnvanAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UnvanId");

                    b.ToTable("Unvanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
